apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.27.187.254
      peer-asn: 65531
      my-asn: 65524
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.28.255.64/26