apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: baremetal-cluster
  name: baremetal-cluster
---
apiVersion: devops.gostship.io/v1
kind: Cluster
metadata:
  name: baremetal-cluster
  namespace: baremetal-cluster
  annotations:
    k8s.io/apiSvcVip: "10.248.224.217"
    k8s.io/action: EnsureExtKubeconfig,EnsureCni
spec:
  pause: false
  tenantID: kunkka
  displayName: demo
  type: Baremetal
  version: v1.18.5
  networkType: eth0
  clusterCIDR: 10.91.0.0/16
  serviceCIDR: 10.92.0.0/16
  dnsDomain: cluster.local
  publicAlternativeNames:
    - baremetalt1.dke.k8s.io
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    ha:
      thirdParty:
        vip: "10.248.224.217"
        vport: 443
    files:
      - src: "/k8s/bin/k9s"
        dst: "/usr/local/bin/k9s"
    hooks:
      cniInstall: flannel
  properties:
    maxNodePodNum: 64
  machines:
    - ip: 10.248.224.183
      port: 22
      username: root
      password: ""
    - ip: 10.248.224.201
      port: 22
      username: root
      password: ""
    - ip: 10.248.224.199
      port: 22
      username: root
      password: ""
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    "bind-address": "0.0.0.0"
  schedulerExtraArgs:
    "bind-address": "0.0.0.0"
  dockerExtraArgs:
    registry-mirrors: https://4xr1qpsp.mirror.aliyuncs.com
    version: 19.03.9
---
apiVersion: devops.gostship.io/v1
kind: Machine
metadata:
  labels:
    name: 10.248.224.210
  name: 10.248.224.210
  namespace: baremetal-cluster
spec:
  clusterName: baremetal-cluster
  type: Baremetal
  machine:
    ip: 10.248.224.210
    port: 22
    username: root
    password: "hNKKTFCAOp6r58A"
  feature:
    hooks:
      installType: kubeadm