apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: cvmt2-cluster
  name: cvmt2-cluster
---
apiVersion: devops.gostship.io/v1
kind: Cluster
metadata:
  name: cvmt2-cluster
  namespace: cvmt2-cluster
  annotations:
    k8s.io/apiSvcVip: 10.248.224.210
    k8s.io/action: EnsureCni,EnsureMetricsServer
spec:
  pause: false
  tenantID: kunkka
  displayName: demo
  type: Baremetal
  version: 1.18.5
  networkType: eth0
  clusterCIDR: 10.91.0.0/16
  serviceCIDR: 10.92.0.0/16
  dnsDomain: cluster.local
  publicAlternativeNames:
    - cvmt2.dke.k8s.io
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    ha:
      thirdParty:
        vip: "10.248.224.150"
        vport: 6443
    files:
      - src: "k8s/linuxbin/k9s"
        dst: "/usr/local/bin/k9s"
    hooks:
      cniInstall: flannel
  properties:
    maxNodePodNum: 64
  machines:
    - ip: 10.248.224.210
      port: 22
      username: root
      password: "UVK4AfcSuEQTK-LH-Lk1Fy"
    - ip: 10.248.224.172
      port: 22
      username: root
      password: "UVK4AfcSuEQTK-LH-Lk1Fy"
    - ip: 10.248.224.176
      port: 22
      username: root
      password: "UVK4AfcSuEQTK-LH-Lk1Fy"
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    "bind-address": "0.0.0.0"
  schedulerExtraArgs:
    "bind-address": "0.0.0.0"
  dockerExtraArgs:
    registry-mirrors: https://4xr1qpsp.mirror.aliyuncs.com
    version: 19.03.9