apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: hosted-b-cluster
  name: hosted-b-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: hosted-b-cluster
  name: etcd
  labels:
    app: etcd
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                namespaces:
                  - hosted-b-cluster
                labelSelector:
                  matchLabels:
                    app: etcd
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: etcd
          image: symcn.tencentcloudcr.com/symcn/kubernetes:v1.16.13
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: INITIAL_CLUSTER_SIZE
              value: "3"
            - name: CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: datadir
              mountPath: /var/run/etcd
          command:
            - /bin/sh
            - -c
            - |
              PEERS="etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
              exec etcd --name ${HOSTNAME} \
                --listen-peer-urls http://0.0.0.0:2380 \
                --listen-client-urls http://0.0.0.0:2379 \
                --advertise-client-urls http://${HOSTNAME}.etcd:2379 \
                --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
                --initial-cluster-token etcd-cluster-1 \
                --initial-cluster ${PEERS} \
                --initial-cluster-state new \
                --data-dir /var/run/etcd/default.etcd
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: local-storage
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: hosted-b-cluster
  name: etcd
  labels:
    app: etcd
spec:
  ports:
    - port: 2380
      name: etcd-server
    - port: 2379
      name: etcd-client
  clusterIP: None
  selector:
    app: etcd
  publishNotReadyAddresses: true
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: hosted-b-cluster
  name: etcd-pdb
  labels:
    pdb: etcd
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: etcd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    createdBy: controller
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd0-hosted-b-cluster-lpv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /web/hosted-b-cluster
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.248.224.183
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd2-hosted-b-cluster-lpv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /web/hosted-b-cluster
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.248.224.199
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd1-hosted-b-cluster-lpv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /web/hosted-b-cluster
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.248.224.201
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: devops.gostship.io/v1
kind: Cluster
metadata:
  name: hosted-b-cluster
  namespace: hosted-b-cluster
  annotations:
    k8s.io/action: EnsureExtKubeconfig,EnsureAddons,EnsureFlannel
spec:
  pause: false
  tenantID: kunkka
  displayName: demo
  type: Hosted
  version: v1.16.13
  networkType: eth0
  clusterCIDR: 10.98.0.0/16
  serviceCIDR: 10.99.0.0/16
  dnsDomain: cluster.local
  publicAlternativeNames:
    - hostedb.dke.k8s.io
    - kube-apiserver
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    ha:
      thirdParty:
        vip: "10.248.224.183"
        vport: 31443
    files:
      - src: "/usr/local/bin/k9s"
        dst: "/usr/local/bin/k9s"
    hooks:
      PostCniInstall: flannel
  properties:
    maxNodePodNum: 64
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-policy-file: "/etc/kubernetes/audit-policy.yaml"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    "bind-address": "0.0.0.0"
  schedulerExtraArgs:
    "bind-address": "0.0.0.0"
  dockerExtraArgs:
    registry-mirrors: https://4xr1qpsp.mirror.aliyuncs.com
    version: 19.03.9
---
apiVersion: devops.gostship.io/v1
kind: Machine
metadata:
  labels:
    name: 10.248.224.176
  name: 10.248.224.176
  namespace: hosted-a-cluster
spec:
  clusterName: hosted-b-cluster
  type: Hosted
  machine:
    ip: 10.248.224.176
    port: 22
    username: root
    password: "UVK4AfcSuEQTK-LH-Lk1Fy"
  feature:
    hooks:
      installType: kubeadm
---
apiVersion: devops.gostship.io/v1
kind: Machine
metadata:
  labels:
    name: 10.248.224.211
  name: 10.248.224.211
  namespace: hosted-b-cluster
spec:
  clusterName: hosted-b-cluster
  type: Hosted
  machine:
    ip: 10.248.224.211
    port: 22
    username: root
    password: "UVK4AfcSuEQTK-LH-Lk1Fy"
  feature:
    hooks:
      installType: kubeadm