apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: cvm-admin
  name: cvm-admin
---
apiVersion: devops.gostship.io/v1
kind: Cluster
metadata:
  name: cvm2-cluster
  namespace: cvm-admin
spec:
  pause: false
  tenantID: k8s
  displayName: demo
  type: Baremetal
  version: 1.18.2
  networkType: eth0
  clusterCIDR: 10.27.184.0/21
  serviceCIDR: 172.27.248.0/22
  dnsDomain: cluster.local
  publicAlternativeNames:
    - apivip2.dke.k8s.io
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    hooks:
      PostCniInstall: flannel
  properties:
    maxNodePodNum: 64
  machines:
    - ip: 10.27.187.242
      port: 22
      username: root
      password: "123456"
    - ip: 10.27.187.241
      port: 22
      username: root
      password: "123456"
    - ip: 10.27.187.243
      port: 22
      username: root
      password: "123456"
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    "bind-address": "0.0.0.0"
  schedulerExtraArgs:
    "bind-address": "0.0.0.0"
  dockerExtraArgs:
    registry-mirrors: https://4xr1qpsp.mirror.aliyuncs.com
    version: 19.03.8