apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: cvm-admin
  name: cvm-admin
---
apiVersion: devops.gostship.io/v1
kind: Cluster
metadata:
  name: k8s-cvm-cluster
  namespace: cvm-admin
spec:
  tenantID: k8s
  displayName: demo
  type: Baremetal
  version: 1.18.2
  networkType: eth0
  clusterCIDR: 172.10.0.0/16
  serviceCIDR: 10.96.0.0/16
  dnsDomain: cluster.local
  publicAlternativeNames:
    - vip1.dke.k8s.io
  features:
    ipvs: true
    internalLB: true
    enableMasterSchedule: true
    ha:
      dke:
        vip: "10.248.224.253"
  properties:
    maxNodePodNum: 64
  machines:
    - ip: 10.248.224.201
      port: 22
      username: root
      password: "UVK4AfcSuEQTK-LH-Lk1Fy"
    - ip: 10.248.224.172
      port: 22
      username: root
      password: "UVK4AfcSuEQTK-LH-Lk1Fy"
    - ip: 10.248.224.176
      port: 22
      username: root
      password: "UVK4AfcSuEQTK-LH-Lk1Fy"
  apiServerExtraArgs:
    audit-log-maxage: "30"
    audit-log-maxbackup: "3"
    audit-log-maxsize: "100"
    audit-log-truncate-enabled: "true"
    audit-log-path: "/var/log/kubernetes/k8s-audit.log"
  controllerManagerExtraArgs:
    "bind-address": "0.0.0.0"
  schedulerExtraArgs:
    "bind-address": "0.0.0.0"
  dockerExtraArgs:
    registry-mirrors: https://4xr1qpsp.mirror.aliyuncs.com
    version: 19.03.8