# permissions for end users to view virtulclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtulcluster-viewer-role
rules:
- apiGroups:
  - devops.gostship.io
  resources:
  - virtulclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.gostship.io
  resources:
  - virtulclusters/status
  verbs:
  - get
