# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: symcn.tencentcloudcr.com/symcn/kunkka-console
  tag: v0.0.4-dev1617
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8000
  nodePort: 30882

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    projectcontour.io/websocket-routes: "/"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: devapi.sym.xx.com
    # - host: testapi-djj.sym.xx.com
      paths: ["/"]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

#healthPath:
#  liveness: "/live"
#  readiness: "/ready"
#
#rbac:
#  name: kunkka-api
#  rules:
#  - apiGroups: ["devops.gostship.io"]
#    resources: ["*"]
#    verbs: ["*"]
#  - apiGroups: [""]
#    resources: ["pods", "services", "endpoints", "configmaps"]
#    verbs: ["*"]
#  - apiGroups: ["apps"]
#    resources: ["deployments", "statefulsets"]
#    verbs: ["*"]
#  - apiGroups: [""]
#    resources: ["events", "pods/portforward"]
#    verbs: ["*"]

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 0.1
    memory: 256Mi
  requests:
    cpu: 0.1
    memory: 256Mi

nodeSelector: {}

tolerations: []
