apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EZ3dNekV5TVRJek1Wb1hEVE13TURnd01URXlNVEl6TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3FECnd2Wm5ZWDltM082dEJFaWxYU2p4Rnk3cTU1UGxuRC90SjRYK2VSd28wUDVucmc1amJWaFUxbDV5M0lnZjFGdjIKeWMzb0ZyM2lnL1VmcEw4a2l1ZENHLzJFZVVQV3kva05PNmV1ZmFXOWN0MXBYTEtKblIybVBZUEFhb2JrcGxqZwp3eEIxaXBiNlYvOUtuYVlaVEV0bSswcnBIK0VsV0JIVGgrK0F6K3ZYbzlBZzYydmpnOTVqWWhpcTZsNnh6cnYwCkJsRDVOQ2hzVlJPazdTTG5PZHprNlFYbmJTdEI3MncvU2FpQW82cis2QjhlYlpnZzNaNld4bE5FUkpIQkVQU3EKb1RaNlZSb0RmODlVZzZFYlBjZFN3ZGhtS0FLbEpjZmNYV2JuWmY2azdoclJsMG9Uc0xoZFpTeXBVUnU3ZVdiVAp0eVdkMVhrdjBJajBvRnVWTjU4Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJcSsxWkpNaWpDNlhjNEhrUE1aSFozVXZsNFMKU0ovZzBTSEYrREhIbTk4VGRWR053d2NscnZhRFB1Uzd2Yy9WSVpsdDhmTnQwbE42ZFNDQ3JhMmVoQ2E2YXV2cApYRm9teXgwMWpmQkJDR3V4cGJKaVV5YUVzZGdyekpTRDZLZHlMNUFKSzdaazdZaWxBcys4amkvV3VlZWZyT1F6CjJXZEN5QUxsWVRMemhQWVlheFFsMzlmQTlWcWR6OXFIeGpEcmNVL2IxN0ozWUdWOXFHN2g5K1VrY0QyS2pRV0MKRUYxZ0N0MDNuQ0hReEgxbUd5QXBOWEEyL3R0OFk1ZWgxc3E1RDcyMkNSSjl5cTl0bDliUDZjWkhORi9PZ0JXNwpHbDZzTUp1V2RBa0JqZjFhTWY0SEhJZ1VMNUh0aDlsc25FTnFYcVhWaXRETi9LTFpOc2NUY0NXTW5jUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://cls-p7vjyie1.ccs.tencent-cloud.com
  name: local
contexts:
- context:
    cluster: local
    user: admin
  name: cls-p7vjyie1-context-default
current-context: cls-p7vjyie1-context-default
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: aP0b7qW37RBd1ttTpTwmHjl51TKK8NtL