apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01UQXdPVEF6TWpnMU5Gb1hEVE13TVRBd056QXpNamcxTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSlJ3ClNhdHR2blU0SUhaMG51SFNtblZiaGRySkJuMTJkZnRLVmVHaTdYMDc5SGtUWGRQNFpXcHBqN3E3Q0t2NklXajEKMVlTWk5ZblN0dlNKYlBqOEx0NlZBT1BxUy9YdzVwbERweXEzN0dTbVE3VVYrR2hvckwxMU4rV25EQ0d0N0ZPcAowVU5RRy9IVlJRcUErTjJWeDJ0b3BROE8zbm5zRzNPY3R3aFhPWHF0TE5iOUdWdzFZT3dtZ3ZvaGRrRWdWZy9HCmlhandWR2k0V3RWaGJ5Y2ZZU3A2RjZTaFFBWVZXaFRuNVdMUktwNlpGckZoWmdoQ25Jck0wbGRwZ0FlZ1Rtb20KZE4vMHU5MUdyQXp6YmdwM1RQU2xSUkYvSUhIWU12bVRtQmhwMkovZlYzWEc0Mm03MEM2WFJTVERMcjRkZHVhUAo1Zi85SnRhcU5nRW9ZQmh4V0xNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJMyttTG90M1ovejBuYlJvNjJyb1F1ZUxFRnoKV1Zpd1IvTjdiZkkvRmJGRUZkTUY4R1c2KytVVkdnMWsvUWEwZDBodEdPQ1VPSTdDRjhuMy96TjBOSEZFRFk3dwo2V3Bud0ZuWFl2OHVxRGhvRVRXU29TUEtyVVJLVW5ta1FMa25NNkhMQUlJbDhUc2lSTSt1MEF1UTBpRDdLRXdvCmozU3IvZWw5eXBkalJ0TFhvRjJsZys1WTRwbHpWYzdYclVmRmdFVXFERlBmMTNlb0FqMzdFUVlNOGpNSG1OTSsKRGJ5VzJWcE54NjhwUk9KbnladTdhT1VPaEE4eEtSU2FWY0NKNkE1NmRWekRXVEcyVWg5b0paamxYT3RuRVNLQwpUM3crcUF2STdjYk1iZ2E5blE5OENwVnJpVHdPZnFpc0tVN3RZOGxpdjlwNVM1cXNqUExCTkc2T05rST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://cls-ir4n6hen.ccs.tencent-cloud.com
  name: local
contexts:
- context:
    cluster: local
    user: admin
  name: cls-ir4n6hen-context-default
current-context: cls-ir4n6hen-context-default
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: Vh8akSqR20j4d0iAuqgQIWnZGuLc22Vo