# Default values for controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: symcn.tencentcloudcr.com/symcn/kunkka
  tag: v0.0.5-dev13
  pullPolicy: Always
  logLevel: 4
  leader: true
  threadiness: 1

nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

#healthPath:
#  liveness: "/live"
#  readiness: "/ready"

rbac:
  name: kunkka-controller
  rules:
  - apiGroups: ["devops.gostship.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events", "pods/portforward"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["*"]

resources:
  limits:
    cpu: 0.5
    memory: 2048Mi
  requests:
    cpu: 0.2
    memory: 512Mi

nodeSelector: {}

